services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeyMoon\DoctrinePostgresEnum\Doctrine\Provider\MetaDataProviderInterface:
    class: HeyMoon\DoctrinePostgresEnum\Doctrine\Provider\MetaDataProvider

  doctrine_enum.column_listener:
    class: HeyMoon\DoctrinePostgresEnum\Doctrine\Listener\DoctrineEnumColumnListener
    tags:
      - { name: doctrine.event_subscriber }
