name: Test
run-name: ${{ github.actor }} is testing heymoon/doctrine-psql-enum
on:
  workflow_dispatch: {}
  push:
    paths:
      - config
      - src
      - tests
      - composer.json
      - Makefile
      - phpunit.xml
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - run: make test
      - run: make network.clear
      - name: Upload test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: test-reports/tests.xml
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: test-reports/clover.xml
